### ISSUE TITLE
Implement the airquality API 

### ISSUE THREAD

**Issue by gblasut** [FedeMDR/wizard_LSPD_exam#16]
Implement the airquality API. The aim is to print (display )the air quality for each bnb.

**Comment by FedeMDR** [comment]
started working on it, still to finish

**Comment by TrivialHarp16** [comment]
Developed 'air_quality()' on the backend to pass the needed data to the front end to display the most recent air quality index measurement in the 5 main neighbourhood of NYC. 

@FedeMDR Develop the HTML code and the front end to complete the issue

**Comment by TrivialHarp16** [comment]
Developed 'get_bnb_by_neighborhood(target_neighborhood)' to return all the BnB grouped by the inputted neighborhood

**Comment by FedeMDR** [comment]
I developed the HTML page to show the AQI
@gblasut Develop a function that adds a label to inform the user about the level of air quality

**Comment by gblasut** [comment]
I developed the function, and now @martinaleccia will implement the HTML

**Comment by martinaleccia** [comment]
I implemented the HTML labels to display the air quality level
